name: Joel Gillman
baseurl: ''
permalink: /:year/:month/:title
paginate: 2
paginate_path: "page-num"

# RSS Generator Plugin
url: http://joelgillman.com/blog/
author: Joel Gillman

highlighter: pygments

markdown: redcarpet
redcarpet:
  extensions:
    - no_intra_emphasis
    - space_after_headers
    - strikethrough
    - superscript
    - tables

sass:
  sass_dir: _sass

# Image Tag Plugin
image:
  source: assets/img
  output: i
  presets:
    post:
      attr:
        class: img-responsive img-thumbnail
        itemprop: image
      width: 750

